### ISSUE TITLE
PHP Fatal error:  Declaration of phpDocumentor\Reflection\Php\ProjectFactory::create($name, array $files)

### ISSUE THREAD

**Issue by SilberMa** [juliushaertl/phpdoc-to-rst#14]
Hi there,

> PHP Fatal error:  Declaration of phpDocumentor\Reflection\Php\ProjectFactory::create($name, array $files) must be compatible with phpDocumentor\Reflection\ProjectFactory::create($name, array $files): phpDocumentor\Reflection\Project in /app/vendor/juliushaertl/phpdoc-to-rst/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/ProjectFactory.php on line 25

shows up when i try 

`./vendor/bin/phpdoc-to-rst -vvv generate /app/documentation/ /app/src/TestBundle
`
I am using php 7.1.13.
It's a normal namespace testcase.
So we got: TestBundle(with class) and underneath NewFolder/MyCommand.php

Are you still maintaining this? 
Do you have any idea how to solve this?

Kind regards.

**Comment by juliusknorr** [comment]
@SilberMa Yes, this repo is still maintained. Thanks for reporting the issue. 

It seems that phpdocumentor/reflection-common introduced type hinting while phpdocumentor/reflection doesn't at the moment. For now I've locked the reflection-common dependency to a fixed version with 1a48891. That should fix the issue.

**Comment by SilberMa** [comment]
Thank you very much! 

That did the trick :)
